###
  Template generated by vue-cli
  https://github.com/webartisans-es/vue-component

  Component {{capitalize name}}
  @author {{author}}
###


class {{capitalize name}}

###
Name of the component
###
name: '{{capitalize name}}'

###
  The attributes of this component
   @returns Object
###
data: () =>
  return {}


###
  The Component is mounted to the DOM
###
mounted: () =>
  console.log "{{capitalize name}} is ready"


module.export = new {{capitalize name}}
