/**
 * Template generated by vue-cli
 * https://github.com/webartisans-es/vue-component
 *
 * Component {{capitalize name}}
 * @author {{author}}
 */

export default {
	/**
	 * Name of the component
	 */
	name: '{{capitalize name}}',

	/**
	 * The attributes of this component
	 * @returns Object
	 */
	data () {
		return {}
	},

	/**
	 * The public properties for this component
	 * @returns Object
	 * https://vuejs.org/v2/api/#props
	 */
	props: {

	},

	/**
	 * The computed properties for this component
	 * @returns Object
	 * https://vuejs.org/v2/api/#computed
	 */
	computed: {

	},

	/**
	 * The methods properties for this component
	 * @returns Object
	 * https://vuejs.org/v2/api/#methods
	 */
	methods: {

	},

	/**
	 * Before Create hook for component
	 * https://vuejs.org/v2/api/#beforeCreate
	 */
	beforeCreate () {

	},

	/**
	 * Before Create hook for component
	 * https://vuejs.org/v2/api/#created
	 */
	created () {

	},

	/**
	 * Mounted hook for component
	 * https://vuejs.org/v2/api/#mounted
	 */
	mounted () {

	}
}
